spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: StorylineFever68

#JPA Settings
  jpa:
    hibernate:
      ddl-auto: create






